apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: unsa-matricula
data:
  DB_HOST:    postgres-service
  DB_PORT:    "5432"
  DB_NAME:    matricula
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  PORT:       "3000"
  BACKEND_URL: http://backend-service:3000
