apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: unsa-matricula
type: Opaque
stringData:
  DB_USER:     matricula
  DB_PASSWORD: matricula123
  POSTGRES_USER:     matricula
  POSTGRES_PASSWORD: matricula123
  POSTGRES_DB:       matricula
