alertmanager:
  enabled: false

grafana:
  adminPassword: unsa-grafana-demo
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    storageSpec: {}

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi

nodeExporter:
  enabled: true
